version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd

  queue:
    image: redis
    restart: always

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  app:
    image: magdz/insta-app
    ports:
      - "80:3000"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    depends_on:
      - db
      - queue
      - search

  worker:
    image: magdz/insta-worker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    depends_on:
      - db
      - queue

volumes:
  esdata:
    driver: local
