version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd

  app:
    image: magdz/insta-app
    ports:
      - "3000:3000"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    depends_on:
      - db

  queue:
    image: redis
    restart: always

  chat:
    image: magdz/insta-chat
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - queue
